// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "viron": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/yudppp/viron-goa/design
// --out=$(GOPATH)/src/github.com/yudppp/viron-goa
// --version=v1.3.1

package app
